name: Vue 3 CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Sử dụng Node.js 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: Setup SSH for VPS
        env:
          VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$VPS_SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

      - name: Build Docker Image
        run: docker build -t ${{ secrets.VPS_IP }}:5000/vue3-app:latest .

      - name: Push Docker Image to VPS Registry
        run: docker push ${{ secrets.VPS_IP }}:5000/vue3-app:latest

      - name: Deploy to VPS
        env:
          VPS_IP: ${{ secrets.VPS_IP }}
          VPS_USER: 'root'
        run: |
          ssh -i ~/.ssh/id_ed25519 $VPS_USER@$VPS_IP << EOF
            docker pull ${{ secrets.VPS_IP }}:5000/vue3-app:latest
            docker stop vue3-app || true
            docker rm vue3-app || true
            docker run -d --name vue3-app -p 80:80 ${{ secrets.VPS_IP }}:5000/vue3-app:latest
          EOF
